// Code generated by gocygen. DO NOT EDIT.
package label

type CountryName string

func (c CountryName) String() string {
	return string(c)
}

const (
	AfghanistanCountry                                       CountryName = `AFGHANISTAN`
	AlbaniaCountry                                           CountryName = `ALBANIA`
	AlgeriaCountry                                           CountryName = `ALGERIA`
	AmericanSamoaCountry                                     CountryName = `AMERICAN SAMOA`
	AndorraCountry                                           CountryName = `ANDORRA`
	AngolaCountry                                            CountryName = `ANGOLA`
	AnguillaCountry                                          CountryName = `ANGUILLA`
	AntiguaAndBarbudaCountry                                 CountryName = `ANTIGUA AND BARBUDA`
	ArgentinaCountry                                         CountryName = `ARGENTINA`
	ArmeniaCountry                                           CountryName = `ARMENIA`
	ArubaCountry                                             CountryName = `ARUBA`
	AustraliaCountry                                         CountryName = `AUSTRALIA`
	AustriaCountry                                           CountryName = `AUSTRIA`
	AzerbaijanCountry                                        CountryName = `AZERBAIJAN`
	BahamasTheCountry                                        CountryName = `BAHAMAS (THE)`
	BahrainCountry                                           CountryName = `BAHRAIN`
	BangladeshCountry                                        CountryName = `BANGLADESH`
	BarbadosCountry                                          CountryName = `BARBADOS`
	BelarusCountry                                           CountryName = `BELARUS`
	BelgiumCountry                                           CountryName = `BELGIUM`
	BelizeCountry                                            CountryName = `BELIZE`
	BeninCountry                                             CountryName = `BENIN`
	BermudaCountry                                           CountryName = `BERMUDA`
	BhutanCountry                                            CountryName = `BHUTAN`
	BoliviaPlurinationalStateOfCountry                       CountryName = `BOLIVIA (PLURINATIONAL STATE OF)`
	BonaireSintEustatiusAndSabaCountry                       CountryName = `BONAIRE, SINT EUSTATIUS AND SABA`
	BosniaAndHerzegovinaCountry                              CountryName = `BOSNIA AND HERZEGOVINA`
	BotswanaCountry                                          CountryName = `BOTSWANA`
	BouvetIslandCountry                                      CountryName = `BOUVET ISLAND`
	BrazilCountry                                            CountryName = `BRAZIL`
	BritishIndianOceanTerritoryTheCountry                    CountryName = `BRITISH INDIAN OCEAN TERRITORY (THE)`
	BruneiDarussalamCountry                                  CountryName = `BRUNEI DARUSSALAM`
	BulgariaCountry                                          CountryName = `BULGARIA`
	BurkinaFasoCountry                                       CountryName = `BURKINA FASO`
	BurundiCountry                                           CountryName = `BURUNDI`
	CaboVerdeCountry                                         CountryName = `CABO VERDE`
	CambodiaCountry                                          CountryName = `CAMBODIA`
	CameroonCountry                                          CountryName = `CAMEROON`
	CanadaCountry                                            CountryName = `CANADA`
	CaymanIslandsTheCountry                                  CountryName = `CAYMAN ISLANDS (THE)`
	CentralAfricanRepublicTheCountry                         CountryName = `CENTRAL AFRICAN REPUBLIC (THE)`
	ChadCountry                                              CountryName = `CHAD`
	ChileCountry                                             CountryName = `CHILE`
	ChinaCountry                                             CountryName = `CHINA`
	ChristmasIslandCountry                                   CountryName = `CHRISTMAS ISLAND`
	CocosKeelingIslandsTheCountry                            CountryName = `COCOS (KEELING) ISLANDS (THE)`
	ColombiaCountry                                          CountryName = `COLOMBIA`
	ComorosTheCountry                                        CountryName = `COMOROS (THE)`
	CongoTheCountry                                          CountryName = `CONGO (THE)`
	CongoTheDemocraticRepublicOfTheCountry                   CountryName = `CONGO (THE DEMOCRATIC REPUBLIC OF THE)`
	CookIslandsTheCountry                                    CountryName = `COOK ISLANDS (THE)`
	CostaRicaCountry                                         CountryName = `COSTA RICA`
	CroatiaCountry                                           CountryName = `CROATIA`
	CteDivoireCountry                                        CountryName = `CÔTE D'IVOIRE`
	CubaCountry                                              CountryName = `CUBA`
	CuraaoCountry                                            CountryName = `CURAÇAO`
	CyprusCountry                                            CountryName = `CYPRUS`
	CzechiaCountry                                           CountryName = `CZECHIA`
	DenmarkCountry                                           CountryName = `DENMARK`
	DjiboutiCountry                                          CountryName = `DJIBOUTI`
	DominicaCountry                                          CountryName = `DOMINICA`
	DominicanRepublicTheCountry                              CountryName = `DOMINICAN REPUBLIC (THE)`
	EcuadorCountry                                           CountryName = `ECUADOR`
	EgyptCountry                                             CountryName = `EGYPT`
	ElSalvadorCountry                                        CountryName = `EL SALVADOR`
	EquatorialGuineaCountry                                  CountryName = `EQUATORIAL GUINEA`
	EritreaCountry                                           CountryName = `ERITREA`
	EstoniaCountry                                           CountryName = `ESTONIA`
	EswatiniCountry                                          CountryName = `ESWATINI`
	EthiopiaCountry                                          CountryName = `ETHIOPIA`
	EuropeanUnionCountry                                     CountryName = `EUROPEAN UNION`
	FalklandIslandsTheMalvinasCountry                        CountryName = `FALKLAND ISLANDS (THE) [MALVINAS]`
	FaroeIslandsTheCountry                                   CountryName = `FAROE ISLANDS (THE)`
	FijiCountry                                              CountryName = `FIJI`
	FinlandCountry                                           CountryName = `FINLAND`
	FranceCountry                                            CountryName = `FRANCE`
	FrenchGuianaCountry                                      CountryName = `FRENCH GUIANA`
	FrenchPolynesiaCountry                                   CountryName = `FRENCH POLYNESIA`
	FrenchSouthernTerritoriesTheCountry                      CountryName = `FRENCH SOUTHERN TERRITORIES (THE)`
	GabonCountry                                             CountryName = `GABON`
	GambiaTheCountry                                         CountryName = `GAMBIA (THE)`
	GeorgiaCountry                                           CountryName = `GEORGIA`
	GermanyCountry                                           CountryName = `GERMANY`
	GhanaCountry                                             CountryName = `GHANA`
	GibraltarCountry                                         CountryName = `GIBRALTAR`
	GreeceCountry                                            CountryName = `GREECE`
	GreenlandCountry                                         CountryName = `GREENLAND`
	GrenadaCountry                                           CountryName = `GRENADA`
	GuadeloupeCountry                                        CountryName = `GUADELOUPE`
	GuamCountry                                              CountryName = `GUAM`
	GuatemalaCountry                                         CountryName = `GUATEMALA`
	GuernseyCountry                                          CountryName = `GUERNSEY`
	GuineaCountry                                            CountryName = `GUINEA`
	GuineabissauCountry                                      CountryName = `GUINEA-BISSAU`
	GuyanaCountry                                            CountryName = `GUYANA`
	HaitiCountry                                             CountryName = `HAITI`
	HeardIslandAndMcdonaldIslandsCountry                     CountryName = `HEARD ISLAND AND McDONALD ISLANDS`
	HolySeeTheCountry                                        CountryName = `HOLY SEE (THE)`
	HondurasCountry                                          CountryName = `HONDURAS`
	HongKongCountry                                          CountryName = `HONG KONG`
	HungaryCountry                                           CountryName = `HUNGARY`
	IcelandCountry                                           CountryName = `ICELAND`
	IndiaCountry                                             CountryName = `INDIA`
	IndonesiaCountry                                         CountryName = `INDONESIA`
	InternationalMonetaryFundImfCountry                      CountryName = `INTERNATIONAL MONETARY FUND (IMF) `
	IranIslamicRepublicOfCountry                             CountryName = `IRAN (ISLAMIC REPUBLIC OF)`
	IraqCountry                                              CountryName = `IRAQ`
	IrelandCountry                                           CountryName = `IRELAND`
	IsleOfManCountry                                         CountryName = `ISLE OF MAN`
	IsraelCountry                                            CountryName = `ISRAEL`
	ItalyCountry                                             CountryName = `ITALY`
	JamaicaCountry                                           CountryName = `JAMAICA`
	JapanCountry                                             CountryName = `JAPAN`
	JerseyCountry                                            CountryName = `JERSEY`
	JordanCountry                                            CountryName = `JORDAN`
	KazakhstanCountry                                        CountryName = `KAZAKHSTAN`
	KenyaCountry                                             CountryName = `KENYA`
	KiribatiCountry                                          CountryName = `KIRIBATI`
	KoreaTheDemocraticPeoplesRepublicOfCountry               CountryName = `KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)`
	KoreaTheRepublicOfCountry                                CountryName = `KOREA (THE REPUBLIC OF)`
	KuwaitCountry                                            CountryName = `KUWAIT`
	KyrgyzstanCountry                                        CountryName = `KYRGYZSTAN`
	LandIslandsCountry                                       CountryName = `ÅLAND ISLANDS`
	LaoPeoplesDemocraticRepublicTheCountry                   CountryName = `LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)`
	LatviaCountry                                            CountryName = `LATVIA`
	LebanonCountry                                           CountryName = `LEBANON`
	LesothoCountry                                           CountryName = `LESOTHO`
	LiberiaCountry                                           CountryName = `LIBERIA`
	LibyaCountry                                             CountryName = `LIBYA`
	LiechtensteinCountry                                     CountryName = `LIECHTENSTEIN`
	LithuaniaCountry                                         CountryName = `LITHUANIA`
	LuxembourgCountry                                        CountryName = `LUXEMBOURG`
	MacaoCountry                                             CountryName = `MACAO`
	MadagascarCountry                                        CountryName = `MADAGASCAR`
	MalawiCountry                                            CountryName = `MALAWI`
	MalaysiaCountry                                          CountryName = `MALAYSIA`
	MaldivesCountry                                          CountryName = `MALDIVES`
	MaliCountry                                              CountryName = `MALI`
	MaltaCountry                                             CountryName = `MALTA`
	MarshallIslandsTheCountry                                CountryName = `MARSHALL ISLANDS (THE)`
	MartiniqueCountry                                        CountryName = `MARTINIQUE`
	MauritaniaCountry                                        CountryName = `MAURITANIA`
	MauritiusCountry                                         CountryName = `MAURITIUS`
	MayotteCountry                                           CountryName = `MAYOTTE`
	MemberCountriesOfTheAfricanDevelopmentBankGroupCountry   CountryName = `MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP`
	MexicoCountry                                            CountryName = `MEXICO`
	MicronesiaFederatedStatesOfCountry                       CountryName = `MICRONESIA (FEDERATED STATES OF)`
	MoldovaTheRepublicOfCountry                              CountryName = `MOLDOVA (THE REPUBLIC OF)`
	MonacoCountry                                            CountryName = `MONACO`
	MongoliaCountry                                          CountryName = `MONGOLIA`
	MontenegroCountry                                        CountryName = `MONTENEGRO`
	MontserratCountry                                        CountryName = `MONTSERRAT`
	MoroccoCountry                                           CountryName = `MOROCCO`
	MozambiqueCountry                                        CountryName = `MOZAMBIQUE`
	MyanmarCountry                                           CountryName = `MYANMAR`
	NamibiaCountry                                           CountryName = `NAMIBIA`
	NauruCountry                                             CountryName = `NAURU`
	NepalCountry                                             CountryName = `NEPAL`
	NetherlandsTheCountry                                    CountryName = `NETHERLANDS (THE)`
	NewCaledoniaCountry                                      CountryName = `NEW CALEDONIA`
	NewZealandCountry                                        CountryName = `NEW ZEALAND`
	NicaraguaCountry                                         CountryName = `NICARAGUA`
	NigerTheCountry                                          CountryName = `NIGER (THE)`
	NigeriaCountry                                           CountryName = `NIGERIA`
	NiueCountry                                              CountryName = `NIUE`
	NorfolkIslandCountry                                     CountryName = `NORFOLK ISLAND`
	NorthMacedoniaCountry                                    CountryName = `NORTH MACEDONIA`
	NorthernMarianaIslandsTheCountry                         CountryName = `NORTHERN MARIANA ISLANDS (THE)`
	NorwayCountry                                            CountryName = `NORWAY`
	OmanCountry                                              CountryName = `OMAN`
	PakistanCountry                                          CountryName = `PAKISTAN`
	PalauCountry                                             CountryName = `PALAU`
	PanamaCountry                                            CountryName = `PANAMA`
	PapuaNewGuineaCountry                                    CountryName = `PAPUA NEW GUINEA`
	ParaguayCountry                                          CountryName = `PARAGUAY`
	PeruCountry                                              CountryName = `PERU`
	PhilippinesTheCountry                                    CountryName = `PHILIPPINES (THE)`
	PitcairnCountry                                          CountryName = `PITCAIRN`
	PolandCountry                                            CountryName = `POLAND`
	PortugalCountry                                          CountryName = `PORTUGAL`
	PuertoRicoCountry                                        CountryName = `PUERTO RICO`
	QatarCountry                                             CountryName = `QATAR`
	RomaniaCountry                                           CountryName = `ROMANIA`
	RunionCountry                                            CountryName = `RÉUNION`
	RussianFederationTheCountry                              CountryName = `RUSSIAN FEDERATION (THE)`
	RwandaCountry                                            CountryName = `RWANDA`
	SaintBarthlemyCountry                                    CountryName = `SAINT BARTHÉLEMY`
	SaintHelenaAscensionAndTristanDaCunhaCountry             CountryName = `SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA`
	SaintKittsAndNevisCountry                                CountryName = `SAINT KITTS AND NEVIS`
	SaintLuciaCountry                                        CountryName = `SAINT LUCIA`
	SaintMartinFrenchPartCountry                             CountryName = `SAINT MARTIN (FRENCH PART)`
	SaintPierreAndMiquelonCountry                            CountryName = `SAINT PIERRE AND MIQUELON`
	SaintVincentAndTheGrenadinesCountry                      CountryName = `SAINT VINCENT AND THE GRENADINES`
	SamoaCountry                                             CountryName = `SAMOA`
	SanMarinoCountry                                         CountryName = `SAN MARINO`
	SaoTomeAndPrincipeCountry                                CountryName = `SAO TOME AND PRINCIPE`
	SaudiArabiaCountry                                       CountryName = `SAUDI ARABIA`
	SenegalCountry                                           CountryName = `SENEGAL`
	SerbiaCountry                                            CountryName = `SERBIA`
	SeychellesCountry                                        CountryName = `SEYCHELLES`
	SierraLeoneCountry                                       CountryName = `SIERRA LEONE`
	SingaporeCountry                                         CountryName = `SINGAPORE`
	SintMaartenDutchPartCountry                              CountryName = `SINT MAARTEN (DUTCH PART)`
	SistemaUnitarioDeCompensacionRegionalDePagosSucreCountry CountryName = `SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"`
	SlovakiaCountry                                          CountryName = `SLOVAKIA`
	SloveniaCountry                                          CountryName = `SLOVENIA`
	SolomonIslandsCountry                                    CountryName = `SOLOMON ISLANDS`
	SomaliaCountry                                           CountryName = `SOMALIA`
	SouthAfricaCountry                                       CountryName = `SOUTH AFRICA`
	SouthSudanCountry                                        CountryName = `SOUTH SUDAN`
	SpainCountry                                             CountryName = `SPAIN`
	SriLankaCountry                                          CountryName = `SRI LANKA`
	SudanTheCountry                                          CountryName = `SUDAN (THE)`
	SurinameCountry                                          CountryName = `SURINAME`
	SvalbardAndJanMayenCountry                               CountryName = `SVALBARD AND JAN MAYEN`
	SwedenCountry                                            CountryName = `SWEDEN`
	SwitzerlandCountry                                       CountryName = `SWITZERLAND`
	SyrianArabRepublicCountry                                CountryName = `SYRIAN ARAB REPUBLIC`
	TaiwanProvinceOfChinaCountry                             CountryName = `TAIWAN (PROVINCE OF CHINA)`
	TajikistanCountry                                        CountryName = `TAJIKISTAN`
	TanzaniaUnitedRepublicOfCountry                          CountryName = `TANZANIA, UNITED REPUBLIC OF`
	ThailandCountry                                          CountryName = `THAILAND`
	TimorlesteCountry                                        CountryName = `TIMOR-LESTE`
	TogoCountry                                              CountryName = `TOGO`
	TokelauCountry                                           CountryName = `TOKELAU`
	TongaCountry                                             CountryName = `TONGA`
	TrinidadAndTobagoCountry                                 CountryName = `TRINIDAD AND TOBAGO`
	TunisiaCountry                                           CountryName = `TUNISIA`
	TurkeyCountry                                            CountryName = `TURKEY`
	TurkmenistanCountry                                      CountryName = `TURKMENISTAN`
	TurksAndCaicosIslandsTheCountry                          CountryName = `TURKS AND CAICOS ISLANDS (THE)`
	TuvaluCountry                                            CountryName = `TUVALU`
	UgandaCountry                                            CountryName = `UGANDA`
	UkraineCountry                                           CountryName = `UKRAINE`
	UnitedArabEmiratesTheCountry                             CountryName = `UNITED ARAB EMIRATES (THE)`
	UnitedKingdomOfGreatBritainAndNorthernIrelandTheCountry  CountryName = `UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)`
	UnitedStatesMinorOutlyingIslandsTheCountry               CountryName = `UNITED STATES MINOR OUTLYING ISLANDS (THE)`
	UnitedStatesOfAmericaTheCountry                          CountryName = `UNITED STATES OF AMERICA (THE)`
	UruguayCountry                                           CountryName = `URUGUAY`
	UzbekistanCountry                                        CountryName = `UZBEKISTAN`
	VanuatuCountry                                           CountryName = `VANUATU`
	VenezuelaBolivarianRepublicOfCountry                     CountryName = `VENEZUELA (BOLIVARIAN REPUBLIC OF)`
	VietNamCountry                                           CountryName = `VIET NAM`
	VirginIslandsBritishCountry                              CountryName = `VIRGIN ISLANDS (BRITISH)`
	VirginIslandsUsCountry                                   CountryName = `VIRGIN ISLANDS (U.S.)`
	WallisAndFutunaCountry                                   CountryName = `WALLIS AND FUTUNA`
	WesternSaharaCountry                                     CountryName = `WESTERN SAHARA`
	YemenCountry                                             CountryName = `YEMEN`
	ZambiaCountry                                            CountryName = `ZAMBIA`
	ZimbabweCountry                                          CountryName = `ZIMBABWE`
	Zz01bondMarketsUnitEuropeaneurcoCountry                  CountryName = `ZZ01_Bond Markets Unit European_EURCO`
	Zz02bondMarketsUnitEuropeanemu6Country                   CountryName = `ZZ02_Bond Markets Unit European_EMU-6`
	Zz03bondMarketsUnitEuropeaneua9Country                   CountryName = `ZZ03_Bond Markets Unit European_EUA-9`
	Zz04bondMarketsUnitEuropeaneua17Country                  CountryName = `ZZ04_Bond Markets Unit European_EUA-17`
	Zz06testingcodeCountry                                   CountryName = `ZZ06_Testing_Code`
	Zz07nocurrencyCountry                                    CountryName = `ZZ07_No_Currency`
	Zz08goldCountry                                          CountryName = `ZZ08_Gold`
	Zz09palladiumCountry                                     CountryName = `ZZ09_Palladium`
	Zz10platinumCountry                                      CountryName = `ZZ10_Platinum`
	Zz11silverCountry                                        CountryName = `ZZ11_Silver`
)

var Countries = []CountryName{
	AfghanistanCountry,
	AlbaniaCountry,
	AlgeriaCountry,
	AmericanSamoaCountry,
	AndorraCountry,
	AngolaCountry,
	AnguillaCountry,
	AntiguaAndBarbudaCountry,
	ArgentinaCountry,
	ArmeniaCountry,
	ArubaCountry,
	AustraliaCountry,
	AustriaCountry,
	AzerbaijanCountry,
	BahamasTheCountry,
	BahrainCountry,
	BangladeshCountry,
	BarbadosCountry,
	BelarusCountry,
	BelgiumCountry,
	BelizeCountry,
	BeninCountry,
	BermudaCountry,
	BhutanCountry,
	BoliviaPlurinationalStateOfCountry,
	BonaireSintEustatiusAndSabaCountry,
	BosniaAndHerzegovinaCountry,
	BotswanaCountry,
	BouvetIslandCountry,
	BrazilCountry,
	BritishIndianOceanTerritoryTheCountry,
	BruneiDarussalamCountry,
	BulgariaCountry,
	BurkinaFasoCountry,
	BurundiCountry,
	CaboVerdeCountry,
	CambodiaCountry,
	CameroonCountry,
	CanadaCountry,
	CaymanIslandsTheCountry,
	CentralAfricanRepublicTheCountry,
	ChadCountry,
	ChileCountry,
	ChinaCountry,
	ChristmasIslandCountry,
	CocosKeelingIslandsTheCountry,
	ColombiaCountry,
	ComorosTheCountry,
	CongoTheCountry,
	CongoTheDemocraticRepublicOfTheCountry,
	CookIslandsTheCountry,
	CostaRicaCountry,
	CroatiaCountry,
	CteDivoireCountry,
	CubaCountry,
	CuraaoCountry,
	CyprusCountry,
	CzechiaCountry,
	DenmarkCountry,
	DjiboutiCountry,
	DominicaCountry,
	DominicanRepublicTheCountry,
	EcuadorCountry,
	EgyptCountry,
	ElSalvadorCountry,
	EquatorialGuineaCountry,
	EritreaCountry,
	EstoniaCountry,
	EswatiniCountry,
	EthiopiaCountry,
	EuropeanUnionCountry,
	FalklandIslandsTheMalvinasCountry,
	FaroeIslandsTheCountry,
	FijiCountry,
	FinlandCountry,
	FranceCountry,
	FrenchGuianaCountry,
	FrenchPolynesiaCountry,
	FrenchSouthernTerritoriesTheCountry,
	GabonCountry,
	GambiaTheCountry,
	GeorgiaCountry,
	GermanyCountry,
	GhanaCountry,
	GibraltarCountry,
	GreeceCountry,
	GreenlandCountry,
	GrenadaCountry,
	GuadeloupeCountry,
	GuamCountry,
	GuatemalaCountry,
	GuernseyCountry,
	GuineaCountry,
	GuineabissauCountry,
	GuyanaCountry,
	HaitiCountry,
	HeardIslandAndMcdonaldIslandsCountry,
	HolySeeTheCountry,
	HondurasCountry,
	HongKongCountry,
	HungaryCountry,
	IcelandCountry,
	IndiaCountry,
	IndonesiaCountry,
	InternationalMonetaryFundImfCountry,
	IranIslamicRepublicOfCountry,
	IraqCountry,
	IrelandCountry,
	IsleOfManCountry,
	IsraelCountry,
	ItalyCountry,
	JamaicaCountry,
	JapanCountry,
	JerseyCountry,
	JordanCountry,
	KazakhstanCountry,
	KenyaCountry,
	KiribatiCountry,
	KoreaTheDemocraticPeoplesRepublicOfCountry,
	KoreaTheRepublicOfCountry,
	KuwaitCountry,
	KyrgyzstanCountry,
	LandIslandsCountry,
	LaoPeoplesDemocraticRepublicTheCountry,
	LatviaCountry,
	LebanonCountry,
	LesothoCountry,
	LiberiaCountry,
	LibyaCountry,
	LiechtensteinCountry,
	LithuaniaCountry,
	LuxembourgCountry,
	MacaoCountry,
	MadagascarCountry,
	MalawiCountry,
	MalaysiaCountry,
	MaldivesCountry,
	MaliCountry,
	MaltaCountry,
	MarshallIslandsTheCountry,
	MartiniqueCountry,
	MauritaniaCountry,
	MauritiusCountry,
	MayotteCountry,
	MemberCountriesOfTheAfricanDevelopmentBankGroupCountry,
	MexicoCountry,
	MicronesiaFederatedStatesOfCountry,
	MoldovaTheRepublicOfCountry,
	MonacoCountry,
	MongoliaCountry,
	MontenegroCountry,
	MontserratCountry,
	MoroccoCountry,
	MozambiqueCountry,
	MyanmarCountry,
	NamibiaCountry,
	NauruCountry,
	NepalCountry,
	NetherlandsTheCountry,
	NewCaledoniaCountry,
	NewZealandCountry,
	NicaraguaCountry,
	NigerTheCountry,
	NigeriaCountry,
	NiueCountry,
	NorfolkIslandCountry,
	NorthMacedoniaCountry,
	NorthernMarianaIslandsTheCountry,
	NorwayCountry,
	OmanCountry,
	PakistanCountry,
	PalauCountry,
	PanamaCountry,
	PapuaNewGuineaCountry,
	ParaguayCountry,
	PeruCountry,
	PhilippinesTheCountry,
	PitcairnCountry,
	PolandCountry,
	PortugalCountry,
	PuertoRicoCountry,
	QatarCountry,
	RomaniaCountry,
	RunionCountry,
	RussianFederationTheCountry,
	RwandaCountry,
	SaintBarthlemyCountry,
	SaintHelenaAscensionAndTristanDaCunhaCountry,
	SaintKittsAndNevisCountry,
	SaintLuciaCountry,
	SaintMartinFrenchPartCountry,
	SaintPierreAndMiquelonCountry,
	SaintVincentAndTheGrenadinesCountry,
	SamoaCountry,
	SanMarinoCountry,
	SaoTomeAndPrincipeCountry,
	SaudiArabiaCountry,
	SenegalCountry,
	SerbiaCountry,
	SeychellesCountry,
	SierraLeoneCountry,
	SingaporeCountry,
	SintMaartenDutchPartCountry,
	SistemaUnitarioDeCompensacionRegionalDePagosSucreCountry,
	SlovakiaCountry,
	SloveniaCountry,
	SolomonIslandsCountry,
	SomaliaCountry,
	SouthAfricaCountry,
	SouthSudanCountry,
	SpainCountry,
	SriLankaCountry,
	SudanTheCountry,
	SurinameCountry,
	SvalbardAndJanMayenCountry,
	SwedenCountry,
	SwitzerlandCountry,
	SyrianArabRepublicCountry,
	TaiwanProvinceOfChinaCountry,
	TajikistanCountry,
	TanzaniaUnitedRepublicOfCountry,
	ThailandCountry,
	TimorlesteCountry,
	TogoCountry,
	TokelauCountry,
	TongaCountry,
	TrinidadAndTobagoCountry,
	TunisiaCountry,
	TurkeyCountry,
	TurkmenistanCountry,
	TurksAndCaicosIslandsTheCountry,
	TuvaluCountry,
	UgandaCountry,
	UkraineCountry,
	UnitedArabEmiratesTheCountry,
	UnitedKingdomOfGreatBritainAndNorthernIrelandTheCountry,
	UnitedStatesMinorOutlyingIslandsTheCountry,
	UnitedStatesOfAmericaTheCountry,
	UruguayCountry,
	UzbekistanCountry,
	VanuatuCountry,
	VenezuelaBolivarianRepublicOfCountry,
	VietNamCountry,
	VirginIslandsBritishCountry,
	VirginIslandsUsCountry,
	WallisAndFutunaCountry,
	WesternSaharaCountry,
	YemenCountry,
	ZambiaCountry,
	ZimbabweCountry,
	Zz01bondMarketsUnitEuropeaneurcoCountry,
	Zz02bondMarketsUnitEuropeanemu6Country,
	Zz03bondMarketsUnitEuropeaneua9Country,
	Zz04bondMarketsUnitEuropeaneua17Country,
	Zz06testingcodeCountry,
	Zz07nocurrencyCountry,
	Zz08goldCountry,
	Zz09palladiumCountry,
	Zz10platinumCountry,
	Zz11silverCountry,
}

var CountrySymbols = map[CountryName][]Symbol{
	AfghanistanCountry:                     {AFN},
	AlbaniaCountry:                         {ALL},
	AlgeriaCountry:                         {DZD},
	AmericanSamoaCountry:                   {USD},
	AndorraCountry:                         {EUR},
	AngolaCountry:                          {AOA},
	AnguillaCountry:                        {XCD},
	AntiguaAndBarbudaCountry:               {XCD},
	ArgentinaCountry:                       {ARS},
	ArmeniaCountry:                         {AMD},
	ArubaCountry:                           {AWG},
	AustraliaCountry:                       {AUD},
	AustriaCountry:                         {EUR},
	AzerbaijanCountry:                      {AZN},
	BahamasTheCountry:                      {BSD},
	BahrainCountry:                         {BHD},
	BangladeshCountry:                      {BDT},
	BarbadosCountry:                        {BBD},
	BelarusCountry:                         {BYN},
	BelgiumCountry:                         {EUR},
	BelizeCountry:                          {BZD},
	BeninCountry:                           {XOF},
	BermudaCountry:                         {BMD},
	BhutanCountry:                          {INR, BTN},
	BoliviaPlurinationalStateOfCountry:     {BOB, BOV},
	BonaireSintEustatiusAndSabaCountry:     {USD},
	BosniaAndHerzegovinaCountry:            {BAM},
	BotswanaCountry:                        {BWP},
	BouvetIslandCountry:                    {NOK},
	BrazilCountry:                          {BRL},
	BritishIndianOceanTerritoryTheCountry:  {USD},
	BruneiDarussalamCountry:                {BND},
	BulgariaCountry:                        {BGN},
	BurkinaFasoCountry:                     {XOF},
	BurundiCountry:                         {BIF},
	CaboVerdeCountry:                       {CVE},
	CambodiaCountry:                        {KHR},
	CameroonCountry:                        {XAF},
	CanadaCountry:                          {CAD},
	CaymanIslandsTheCountry:                {KYD},
	CentralAfricanRepublicTheCountry:       {XAF},
	ChadCountry:                            {XAF},
	ChileCountry:                           {CLP, CLF},
	ChinaCountry:                           {CNY},
	ChristmasIslandCountry:                 {AUD},
	CocosKeelingIslandsTheCountry:          {AUD},
	ColombiaCountry:                        {COP, COU},
	ComorosTheCountry:                      {KMF},
	CongoTheCountry:                        {XAF},
	CongoTheDemocraticRepublicOfTheCountry: {CDF},
	CookIslandsTheCountry:                  {NZD},
	CostaRicaCountry:                       {CRC},
	CroatiaCountry:                         {HRK},
	CteDivoireCountry:                      {XOF},
	CubaCountry:                            {CUP, CUC},
	CuraaoCountry:                          {ANG},
	CyprusCountry:                          {EUR},
	CzechiaCountry:                         {CZK},
	DenmarkCountry:                         {DKK},
	DjiboutiCountry:                        {DJF},
	DominicaCountry:                        {XCD},
	DominicanRepublicTheCountry:            {DOP},
	EcuadorCountry:                         {USD},
	EgyptCountry:                           {EGP},
	ElSalvadorCountry:                      {SVC, USD},
	EquatorialGuineaCountry:                {XAF},
	EritreaCountry:                         {ERN},
	EstoniaCountry:                         {EUR},
	EswatiniCountry:                        {SZL},
	EthiopiaCountry:                        {ETB},
	EuropeanUnionCountry:                   {EUR},
	FalklandIslandsTheMalvinasCountry:      {FKP},
	FaroeIslandsTheCountry:                 {DKK},
	FijiCountry:                            {FJD},
	FinlandCountry:                         {EUR},
	FranceCountry:                          {EUR},
	FrenchGuianaCountry:                    {EUR},
	FrenchPolynesiaCountry:                 {XPF},
	FrenchSouthernTerritoriesTheCountry:    {EUR},
	GabonCountry:                           {XAF},
	GambiaTheCountry:                       {GMD},
	GeorgiaCountry:                         {GEL},
	GermanyCountry:                         {EUR},
	GhanaCountry:                           {GHS},
	GibraltarCountry:                       {GIP},
	GreeceCountry:                          {EUR},
	GreenlandCountry:                       {DKK},
	GrenadaCountry:                         {XCD},
	GuadeloupeCountry:                      {EUR},
	GuamCountry:                            {USD},
	GuatemalaCountry:                       {GTQ},
	GuernseyCountry:                        {GBP},
	GuineaCountry:                          {GNF},
	GuineabissauCountry:                    {XOF},
	GuyanaCountry:                          {GYD},
	HaitiCountry:                           {HTG, USD},
	HeardIslandAndMcdonaldIslandsCountry:   {AUD},
	HolySeeTheCountry:                      {EUR},
	HondurasCountry:                        {HNL},
	HongKongCountry:                        {HKD},
	HungaryCountry:                         {HUF},
	IcelandCountry:                         {ISK},
	IndiaCountry:                           {INR},
	IndonesiaCountry:                       {IDR},
	InternationalMonetaryFundImfCountry:    {XDR},
	IranIslamicRepublicOfCountry:           {IRR},
	IraqCountry:                            {IQD},
	IrelandCountry:                         {EUR},
	IsleOfManCountry:                       {GBP},
	IsraelCountry:                          {ILS},
	ItalyCountry:                           {EUR},
	JamaicaCountry:                         {JMD},
	JapanCountry:                           {JPY},
	JerseyCountry:                          {GBP},
	JordanCountry:                          {JOD},
	KazakhstanCountry:                      {KZT},
	KenyaCountry:                           {KES},
	KiribatiCountry:                        {AUD},
	KoreaTheDemocraticPeoplesRepublicOfCountry: {KPW},
	KoreaTheRepublicOfCountry:                  {KRW},
	KuwaitCountry:                              {KWD},
	KyrgyzstanCountry:                          {KGS},
	LandIslandsCountry:                         {EUR},
	LaoPeoplesDemocraticRepublicTheCountry:     {LAK},
	LatviaCountry:                              {EUR},
	LebanonCountry:                             {LBP},
	LesothoCountry:                             {LSL, ZAR},
	LiberiaCountry:                             {LRD},
	LibyaCountry:                               {LYD},
	LiechtensteinCountry:                       {CHF},
	LithuaniaCountry:                           {EUR},
	LuxembourgCountry:                          {EUR},
	MacaoCountry:                               {MOP},
	MadagascarCountry:                          {MGA},
	MalawiCountry:                              {MWK},
	MalaysiaCountry:                            {MYR},
	MaldivesCountry:                            {MVR},
	MaliCountry:                                {XOF},
	MaltaCountry:                               {EUR},
	MarshallIslandsTheCountry:                  {USD},
	MartiniqueCountry:                          {EUR},
	MauritaniaCountry:                          {MRU},
	MauritiusCountry:                           {MUR},
	MayotteCountry:                             {EUR},
	MemberCountriesOfTheAfricanDevelopmentBankGroupCountry: {XUA},
	MexicoCountry:                      {MXN, MXV},
	MicronesiaFederatedStatesOfCountry: {USD},
	MoldovaTheRepublicOfCountry:        {MDL},
	MonacoCountry:                      {EUR},
	MongoliaCountry:                    {MNT},
	MontenegroCountry:                  {EUR},
	MontserratCountry:                  {XCD},
	MoroccoCountry:                     {MAD},
	MozambiqueCountry:                  {MZN},
	MyanmarCountry:                     {MMK},
	NamibiaCountry:                     {NAD, ZAR},
	NauruCountry:                       {AUD},
	NepalCountry:                       {NPR},
	NetherlandsTheCountry:              {EUR},
	NewCaledoniaCountry:                {XPF},
	NewZealandCountry:                  {NZD},
	NicaraguaCountry:                   {NIO},
	NigerTheCountry:                    {XOF},
	NigeriaCountry:                     {NGN},
	NiueCountry:                        {NZD},
	NorfolkIslandCountry:               {AUD},
	NorthMacedoniaCountry:              {MKD},
	NorthernMarianaIslandsTheCountry:   {USD},
	NorwayCountry:                      {NOK},
	OmanCountry:                        {OMR},
	PakistanCountry:                    {PKR},
	PalauCountry:                       {USD},
	PanamaCountry:                      {PAB, USD},
	PapuaNewGuineaCountry:              {PGK},
	ParaguayCountry:                    {PYG},
	PeruCountry:                        {PEN},
	PhilippinesTheCountry:              {PHP},
	PitcairnCountry:                    {NZD},
	PolandCountry:                      {PLN},
	PortugalCountry:                    {EUR},
	PuertoRicoCountry:                  {USD},
	QatarCountry:                       {QAR},
	RomaniaCountry:                     {RON},
	RunionCountry:                      {EUR},
	RussianFederationTheCountry:        {RUB},
	RwandaCountry:                      {RWF},
	SaintBarthlemyCountry:              {EUR},
	SaintHelenaAscensionAndTristanDaCunhaCountry: {SHP},
	SaintKittsAndNevisCountry:                    {XCD},
	SaintLuciaCountry:                            {XCD},
	SaintMartinFrenchPartCountry:                 {EUR},
	SaintPierreAndMiquelonCountry:                {EUR},
	SaintVincentAndTheGrenadinesCountry:          {XCD},
	SamoaCountry:                                 {WST},
	SanMarinoCountry:                             {EUR},
	SaoTomeAndPrincipeCountry:                    {STN},
	SaudiArabiaCountry:                           {SAR},
	SenegalCountry:                               {XOF},
	SerbiaCountry:                                {RSD},
	SeychellesCountry:                            {SCR},
	SierraLeoneCountry:                           {SLL},
	SingaporeCountry:                             {SGD},
	SintMaartenDutchPartCountry:                  {ANG},
	SistemaUnitarioDeCompensacionRegionalDePagosSucreCountry: {XSU},
	SlovakiaCountry:                 {EUR},
	SloveniaCountry:                 {EUR},
	SolomonIslandsCountry:           {SBD},
	SomaliaCountry:                  {SOS},
	SouthAfricaCountry:              {ZAR},
	SouthSudanCountry:               {SSP},
	SpainCountry:                    {EUR},
	SriLankaCountry:                 {LKR},
	SudanTheCountry:                 {SDG},
	SurinameCountry:                 {SRD},
	SvalbardAndJanMayenCountry:      {NOK},
	SwedenCountry:                   {SEK},
	SwitzerlandCountry:              {CHF, CHE, CHW},
	SyrianArabRepublicCountry:       {SYP},
	TaiwanProvinceOfChinaCountry:    {TWD},
	TajikistanCountry:               {TJS},
	TanzaniaUnitedRepublicOfCountry: {TZS},
	ThailandCountry:                 {THB},
	TimorlesteCountry:               {USD},
	TogoCountry:                     {XOF},
	TokelauCountry:                  {NZD},
	TongaCountry:                    {TOP},
	TrinidadAndTobagoCountry:        {TTD},
	TunisiaCountry:                  {TND},
	TurkeyCountry:                   {TRY},
	TurkmenistanCountry:             {TMT},
	TurksAndCaicosIslandsTheCountry: {USD},
	TuvaluCountry:                   {AUD},
	UgandaCountry:                   {UGX},
	UkraineCountry:                  {UAH},
	UnitedArabEmiratesTheCountry:    {AED},
	UnitedKingdomOfGreatBritainAndNorthernIrelandTheCountry: {GBP},
	UnitedStatesMinorOutlyingIslandsTheCountry:              {USD},
	UnitedStatesOfAmericaTheCountry:                         {USD, USN},
	UruguayCountry:                                          {UYU, UYI, UYW},
	UzbekistanCountry:                                       {UZS},
	VanuatuCountry:                                          {VUV},
	VenezuelaBolivarianRepublicOfCountry:                    {VES},
	VietNamCountry:                                          {VND},
	VirginIslandsBritishCountry:                             {USD},
	VirginIslandsUsCountry:                                  {USD},
	WallisAndFutunaCountry:                                  {XPF},
	WesternSaharaCountry:                                    {MAD},
	YemenCountry:                                            {YER},
	ZambiaCountry:                                           {ZMW},
	ZimbabweCountry:                                         {ZWL},
	Zz01bondMarketsUnitEuropeaneurcoCountry:                 {XBA},
	Zz02bondMarketsUnitEuropeanemu6Country:                  {XBB},
	Zz03bondMarketsUnitEuropeaneua9Country:                  {XBC},
	Zz04bondMarketsUnitEuropeaneua17Country:                 {XBD},
	Zz06testingcodeCountry:                                  {XTS},
	Zz07nocurrencyCountry:                                   {XXX},
	Zz08goldCountry:                                         {XAU},
	Zz09palladiumCountry:                                    {XPD},
	Zz10platinumCountry:                                     {XPT},
	Zz11silverCountry:                                       {XAG},
}

var SymbolCountries = map[Symbol][]CountryName{
	AED: {UnitedArabEmiratesTheCountry},
	AFN: {AfghanistanCountry},
	ALL: {AlbaniaCountry},
	AMD: {ArmeniaCountry},
	ANG: {CuraaoCountry, SintMaartenDutchPartCountry},
	AOA: {AngolaCountry},
	ARS: {ArgentinaCountry},
	AUD: {AustraliaCountry, ChristmasIslandCountry, CocosKeelingIslandsTheCountry, HeardIslandAndMcdonaldIslandsCountry, KiribatiCountry, NauruCountry, NorfolkIslandCountry, TuvaluCountry},
	AWG: {ArubaCountry},
	AZN: {AzerbaijanCountry},
	BAM: {BosniaAndHerzegovinaCountry},
	BBD: {BarbadosCountry},
	BDT: {BangladeshCountry},
	BGN: {BulgariaCountry},
	BHD: {BahrainCountry},
	BIF: {BurundiCountry},
	BMD: {BermudaCountry},
	BND: {BruneiDarussalamCountry},
	BOB: {BoliviaPlurinationalStateOfCountry},
	BOV: {BoliviaPlurinationalStateOfCountry},
	BRL: {BrazilCountry},
	BSD: {BahamasTheCountry},
	BTN: {BhutanCountry},
	BWP: {BotswanaCountry},
	BYN: {BelarusCountry},
	BZD: {BelizeCountry},
	CAD: {CanadaCountry},
	CDF: {CongoTheDemocraticRepublicOfTheCountry},
	CHE: {SwitzerlandCountry},
	CHF: {LiechtensteinCountry, SwitzerlandCountry},
	CHW: {SwitzerlandCountry},
	CLF: {ChileCountry},
	CLP: {ChileCountry},
	CNY: {ChinaCountry},
	COP: {ColombiaCountry},
	COU: {ColombiaCountry},
	CRC: {CostaRicaCountry},
	CUC: {CubaCountry},
	CUP: {CubaCountry},
	CVE: {CaboVerdeCountry},
	CZK: {CzechiaCountry},
	DJF: {DjiboutiCountry},
	DKK: {DenmarkCountry, FaroeIslandsTheCountry, GreenlandCountry},
	DOP: {DominicanRepublicTheCountry},
	DZD: {AlgeriaCountry},
	EGP: {EgyptCountry},
	ERN: {EritreaCountry},
	ETB: {EthiopiaCountry},
	EUR: {LandIslandsCountry, AndorraCountry, AustriaCountry, BelgiumCountry, CyprusCountry, EstoniaCountry, EuropeanUnionCountry, FinlandCountry, FranceCountry, FrenchGuianaCountry, FrenchSouthernTerritoriesTheCountry, GermanyCountry, GreeceCountry, GuadeloupeCountry, HolySeeTheCountry, IrelandCountry, ItalyCountry, LatviaCountry, LithuaniaCountry, LuxembourgCountry, MaltaCountry, MartiniqueCountry, MayotteCountry, MonacoCountry, MontenegroCountry, NetherlandsTheCountry, PortugalCountry, RunionCountry, SaintBarthlemyCountry, SaintMartinFrenchPartCountry, SaintPierreAndMiquelonCountry, SanMarinoCountry, SlovakiaCountry, SloveniaCountry, SpainCountry},
	FJD: {FijiCountry},
	FKP: {FalklandIslandsTheMalvinasCountry},
	GBP: {GuernseyCountry, IsleOfManCountry, JerseyCountry, UnitedKingdomOfGreatBritainAndNorthernIrelandTheCountry},
	GEL: {GeorgiaCountry},
	GHS: {GhanaCountry},
	GIP: {GibraltarCountry},
	GMD: {GambiaTheCountry},
	GNF: {GuineaCountry},
	GTQ: {GuatemalaCountry},
	GYD: {GuyanaCountry},
	HKD: {HongKongCountry},
	HNL: {HondurasCountry},
	HRK: {CroatiaCountry},
	HTG: {HaitiCountry},
	HUF: {HungaryCountry},
	IDR: {IndonesiaCountry},
	ILS: {IsraelCountry},
	INR: {BhutanCountry, IndiaCountry},
	IQD: {IraqCountry},
	IRR: {IranIslamicRepublicOfCountry},
	ISK: {IcelandCountry},
	JMD: {JamaicaCountry},
	JOD: {JordanCountry},
	JPY: {JapanCountry},
	KES: {KenyaCountry},
	KGS: {KyrgyzstanCountry},
	KHR: {CambodiaCountry},
	KMF: {ComorosTheCountry},
	KPW: {KoreaTheDemocraticPeoplesRepublicOfCountry},
	KRW: {KoreaTheRepublicOfCountry},
	KWD: {KuwaitCountry},
	KYD: {CaymanIslandsTheCountry},
	KZT: {KazakhstanCountry},
	LAK: {LaoPeoplesDemocraticRepublicTheCountry},
	LBP: {LebanonCountry},
	LKR: {SriLankaCountry},
	LRD: {LiberiaCountry},
	LSL: {LesothoCountry},
	LYD: {LibyaCountry},
	MAD: {MoroccoCountry, WesternSaharaCountry},
	MDL: {MoldovaTheRepublicOfCountry},
	MGA: {MadagascarCountry},
	MKD: {NorthMacedoniaCountry},
	MMK: {MyanmarCountry},
	MNT: {MongoliaCountry},
	MOP: {MacaoCountry},
	MRU: {MauritaniaCountry},
	MUR: {MauritiusCountry},
	MVR: {MaldivesCountry},
	MWK: {MalawiCountry},
	MXN: {MexicoCountry},
	MXV: {MexicoCountry},
	MYR: {MalaysiaCountry},
	MZN: {MozambiqueCountry},
	NAD: {NamibiaCountry},
	NGN: {NigeriaCountry},
	NIO: {NicaraguaCountry},
	NOK: {BouvetIslandCountry, NorwayCountry, SvalbardAndJanMayenCountry},
	NPR: {NepalCountry},
	NZD: {CookIslandsTheCountry, NewZealandCountry, NiueCountry, PitcairnCountry, TokelauCountry},
	OMR: {OmanCountry},
	PAB: {PanamaCountry},
	PEN: {PeruCountry},
	PGK: {PapuaNewGuineaCountry},
	PHP: {PhilippinesTheCountry},
	PKR: {PakistanCountry},
	PLN: {PolandCountry},
	PYG: {ParaguayCountry},
	QAR: {QatarCountry},
	RON: {RomaniaCountry},
	RSD: {SerbiaCountry},
	RUB: {RussianFederationTheCountry},
	RWF: {RwandaCountry},
	SAR: {SaudiArabiaCountry},
	SBD: {SolomonIslandsCountry},
	SCR: {SeychellesCountry},
	SDG: {SudanTheCountry},
	SEK: {SwedenCountry},
	SGD: {SingaporeCountry},
	SHP: {SaintHelenaAscensionAndTristanDaCunhaCountry},
	SLL: {SierraLeoneCountry},
	SOS: {SomaliaCountry},
	SRD: {SurinameCountry},
	SSP: {SouthSudanCountry},
	STN: {SaoTomeAndPrincipeCountry},
	SVC: {ElSalvadorCountry},
	SYP: {SyrianArabRepublicCountry},
	SZL: {EswatiniCountry},
	THB: {ThailandCountry},
	TJS: {TajikistanCountry},
	TMT: {TurkmenistanCountry},
	TND: {TunisiaCountry},
	TOP: {TongaCountry},
	TRY: {TurkeyCountry},
	TTD: {TrinidadAndTobagoCountry},
	TWD: {TaiwanProvinceOfChinaCountry},
	TZS: {TanzaniaUnitedRepublicOfCountry},
	UAH: {UkraineCountry},
	UGX: {UgandaCountry},
	USD: {AmericanSamoaCountry, BonaireSintEustatiusAndSabaCountry, BritishIndianOceanTerritoryTheCountry, EcuadorCountry, ElSalvadorCountry, GuamCountry, HaitiCountry, MarshallIslandsTheCountry, MicronesiaFederatedStatesOfCountry, NorthernMarianaIslandsTheCountry, PalauCountry, PanamaCountry, PuertoRicoCountry, TimorlesteCountry, TurksAndCaicosIslandsTheCountry, UnitedStatesMinorOutlyingIslandsTheCountry, UnitedStatesOfAmericaTheCountry, VirginIslandsBritishCountry, VirginIslandsUsCountry},
	USN: {UnitedStatesOfAmericaTheCountry},
	UYI: {UruguayCountry},
	UYU: {UruguayCountry},
	UYW: {UruguayCountry},
	UZS: {UzbekistanCountry},
	VES: {VenezuelaBolivarianRepublicOfCountry},
	VND: {VietNamCountry},
	VUV: {VanuatuCountry},
	WST: {SamoaCountry},
	XAF: {CameroonCountry, CentralAfricanRepublicTheCountry, ChadCountry, CongoTheCountry, EquatorialGuineaCountry, GabonCountry},
	XAG: {Zz11silverCountry},
	XAU: {Zz08goldCountry},
	XBA: {Zz01bondMarketsUnitEuropeaneurcoCountry},
	XBB: {Zz02bondMarketsUnitEuropeanemu6Country},
	XBC: {Zz03bondMarketsUnitEuropeaneua9Country},
	XBD: {Zz04bondMarketsUnitEuropeaneua17Country},
	XCD: {AnguillaCountry, AntiguaAndBarbudaCountry, DominicaCountry, GrenadaCountry, MontserratCountry, SaintKittsAndNevisCountry, SaintLuciaCountry, SaintVincentAndTheGrenadinesCountry},
	XDR: {InternationalMonetaryFundImfCountry},
	XOF: {BeninCountry, BurkinaFasoCountry, CteDivoireCountry, GuineabissauCountry, MaliCountry, NigerTheCountry, SenegalCountry, TogoCountry},
	XPD: {Zz09palladiumCountry},
	XPF: {FrenchPolynesiaCountry, NewCaledoniaCountry, WallisAndFutunaCountry},
	XPT: {Zz10platinumCountry},
	XSU: {SistemaUnitarioDeCompensacionRegionalDePagosSucreCountry},
	XTS: {Zz06testingcodeCountry},
	XUA: {MemberCountriesOfTheAfricanDevelopmentBankGroupCountry},
	XXX: {Zz07nocurrencyCountry},
	YER: {YemenCountry},
	ZAR: {LesothoCountry, NamibiaCountry, SouthAfricaCountry},
	ZMW: {ZambiaCountry},
	ZWL: {ZimbabweCountry},
}
