// Code generated by gocygen. DO NOT EDIT.
package label

func GetCountries() []CountryName {
	return Countries
}

func GetSymbols() []Symbol {
	return Symbols
}

func GetCurrencies() []Currency {
	var currencies []Currency
	for _, currency := range Currencies {
		currencies = append(currencies, currency)
	}

	return currencies
}

func GetCountriesUsingCurrency(symbol Symbol) []CountryName {
	return SymbolCountries[symbol]
}

func GetCurrenciesUsedCountry(name CountryName) []Currency {
	var currencies []Currency
	symbols, ok := CountrySymbols[name]
	if !ok {
		return nil
	}

	for _, symbol := range symbols {
		currency, ok := Currencies[symbol]
		if !ok {
			continue
		}

		currencies = append(currencies, currency)
	}

	return currencies
}
