// Code generated by gocygen. DO NOT EDIT.
package label

type Symbol string

func (s Symbol) String() string {
	return string(s)
}

const (
	AED Symbol = "AED"
	AFN Symbol = "AFN"
	ALL Symbol = "ALL"
	AMD Symbol = "AMD"
	ANG Symbol = "ANG"
	AOA Symbol = "AOA"
	ARS Symbol = "ARS"
	AUD Symbol = "AUD"
	AWG Symbol = "AWG"
	AZN Symbol = "AZN"
	BAM Symbol = "BAM"
	BBD Symbol = "BBD"
	BDT Symbol = "BDT"
	BGN Symbol = "BGN"
	BHD Symbol = "BHD"
	BIF Symbol = "BIF"
	BMD Symbol = "BMD"
	BND Symbol = "BND"
	BOB Symbol = "BOB"
	BOV Symbol = "BOV"
	BRL Symbol = "BRL"
	BSD Symbol = "BSD"
	BTN Symbol = "BTN"
	BWP Symbol = "BWP"
	BYN Symbol = "BYN"
	BZD Symbol = "BZD"
	CAD Symbol = "CAD"
	CDF Symbol = "CDF"
	CHE Symbol = "CHE"
	CHF Symbol = "CHF"
	CHW Symbol = "CHW"
	CLF Symbol = "CLF"
	CLP Symbol = "CLP"
	CNY Symbol = "CNY"
	COP Symbol = "COP"
	COU Symbol = "COU"
	CRC Symbol = "CRC"
	CUC Symbol = "CUC"
	CUP Symbol = "CUP"
	CVE Symbol = "CVE"
	CZK Symbol = "CZK"
	DJF Symbol = "DJF"
	DKK Symbol = "DKK"
	DOP Symbol = "DOP"
	DZD Symbol = "DZD"
	EGP Symbol = "EGP"
	ERN Symbol = "ERN"
	ETB Symbol = "ETB"
	EUR Symbol = "EUR"
	FJD Symbol = "FJD"
	FKP Symbol = "FKP"
	GBP Symbol = "GBP"
	GEL Symbol = "GEL"
	GHS Symbol = "GHS"
	GIP Symbol = "GIP"
	GMD Symbol = "GMD"
	GNF Symbol = "GNF"
	GTQ Symbol = "GTQ"
	GYD Symbol = "GYD"
	HKD Symbol = "HKD"
	HNL Symbol = "HNL"
	HRK Symbol = "HRK"
	HTG Symbol = "HTG"
	HUF Symbol = "HUF"
	IDR Symbol = "IDR"
	ILS Symbol = "ILS"
	INR Symbol = "INR"
	IQD Symbol = "IQD"
	IRR Symbol = "IRR"
	ISK Symbol = "ISK"
	JMD Symbol = "JMD"
	JOD Symbol = "JOD"
	JPY Symbol = "JPY"
	KES Symbol = "KES"
	KGS Symbol = "KGS"
	KHR Symbol = "KHR"
	KMF Symbol = "KMF"
	KPW Symbol = "KPW"
	KRW Symbol = "KRW"
	KWD Symbol = "KWD"
	KYD Symbol = "KYD"
	KZT Symbol = "KZT"
	LAK Symbol = "LAK"
	LBP Symbol = "LBP"
	LKR Symbol = "LKR"
	LRD Symbol = "LRD"
	LSL Symbol = "LSL"
	LYD Symbol = "LYD"
	MAD Symbol = "MAD"
	MDL Symbol = "MDL"
	MGA Symbol = "MGA"
	MKD Symbol = "MKD"
	MMK Symbol = "MMK"
	MNT Symbol = "MNT"
	MOP Symbol = "MOP"
	MRU Symbol = "MRU"
	MUR Symbol = "MUR"
	MVR Symbol = "MVR"
	MWK Symbol = "MWK"
	MXN Symbol = "MXN"
	MXV Symbol = "MXV"
	MYR Symbol = "MYR"
	MZN Symbol = "MZN"
	NAD Symbol = "NAD"
	NGN Symbol = "NGN"
	NIO Symbol = "NIO"
	NOK Symbol = "NOK"
	NPR Symbol = "NPR"
	NZD Symbol = "NZD"
	OMR Symbol = "OMR"
	PAB Symbol = "PAB"
	PEN Symbol = "PEN"
	PGK Symbol = "PGK"
	PHP Symbol = "PHP"
	PKR Symbol = "PKR"
	PLN Symbol = "PLN"
	PYG Symbol = "PYG"
	QAR Symbol = "QAR"
	RON Symbol = "RON"
	RSD Symbol = "RSD"
	RUB Symbol = "RUB"
	RWF Symbol = "RWF"
	SAR Symbol = "SAR"
	SBD Symbol = "SBD"
	SCR Symbol = "SCR"
	SDG Symbol = "SDG"
	SEK Symbol = "SEK"
	SGD Symbol = "SGD"
	SHP Symbol = "SHP"
	SLL Symbol = "SLL"
	SOS Symbol = "SOS"
	SRD Symbol = "SRD"
	SSP Symbol = "SSP"
	STN Symbol = "STN"
	SVC Symbol = "SVC"
	SYP Symbol = "SYP"
	SZL Symbol = "SZL"
	THB Symbol = "THB"
	TJS Symbol = "TJS"
	TMT Symbol = "TMT"
	TND Symbol = "TND"
	TOP Symbol = "TOP"
	TRY Symbol = "TRY"
	TTD Symbol = "TTD"
	TWD Symbol = "TWD"
	TZS Symbol = "TZS"
	UAH Symbol = "UAH"
	UGX Symbol = "UGX"
	USD Symbol = "USD"
	USN Symbol = "USN"
	UYI Symbol = "UYI"
	UYU Symbol = "UYU"
	UYW Symbol = "UYW"
	UZS Symbol = "UZS"
	VES Symbol = "VES"
	VND Symbol = "VND"
	VUV Symbol = "VUV"
	WST Symbol = "WST"
	XAF Symbol = "XAF"
	XAG Symbol = "XAG"
	XAU Symbol = "XAU"
	XBA Symbol = "XBA"
	XBB Symbol = "XBB"
	XBC Symbol = "XBC"
	XBD Symbol = "XBD"
	XCD Symbol = "XCD"
	XDR Symbol = "XDR"
	XOF Symbol = "XOF"
	XPD Symbol = "XPD"
	XPF Symbol = "XPF"
	XPT Symbol = "XPT"
	XSU Symbol = "XSU"
	XTS Symbol = "XTS"
	XUA Symbol = "XUA"
	XXX Symbol = "XXX"
	YER Symbol = "YER"
	ZAR Symbol = "ZAR"
	ZMW Symbol = "ZMW"
	ZWL Symbol = "ZWL"
)

var Symbols = []Symbol{
	AED,
	AFN,
	ALL,
	AMD,
	ANG,
	AOA,
	ARS,
	AUD,
	AWG,
	AZN,
	BAM,
	BBD,
	BDT,
	BGN,
	BHD,
	BIF,
	BMD,
	BND,
	BOB,
	BOV,
	BRL,
	BSD,
	BTN,
	BWP,
	BYN,
	BZD,
	CAD,
	CDF,
	CHE,
	CHF,
	CHW,
	CLF,
	CLP,
	CNY,
	COP,
	COU,
	CRC,
	CUC,
	CUP,
	CVE,
	CZK,
	DJF,
	DKK,
	DOP,
	DZD,
	EGP,
	ERN,
	ETB,
	EUR,
	FJD,
	FKP,
	GBP,
	GEL,
	GHS,
	GIP,
	GMD,
	GNF,
	GTQ,
	GYD,
	HKD,
	HNL,
	HRK,
	HTG,
	HUF,
	IDR,
	ILS,
	INR,
	IQD,
	IRR,
	ISK,
	JMD,
	JOD,
	JPY,
	KES,
	KGS,
	KHR,
	KMF,
	KPW,
	KRW,
	KWD,
	KYD,
	KZT,
	LAK,
	LBP,
	LKR,
	LRD,
	LSL,
	LYD,
	MAD,
	MDL,
	MGA,
	MKD,
	MMK,
	MNT,
	MOP,
	MRU,
	MUR,
	MVR,
	MWK,
	MXN,
	MXV,
	MYR,
	MZN,
	NAD,
	NGN,
	NIO,
	NOK,
	NPR,
	NZD,
	OMR,
	PAB,
	PEN,
	PGK,
	PHP,
	PKR,
	PLN,
	PYG,
	QAR,
	RON,
	RSD,
	RUB,
	RWF,
	SAR,
	SBD,
	SCR,
	SDG,
	SEK,
	SGD,
	SHP,
	SLL,
	SOS,
	SRD,
	SSP,
	STN,
	SVC,
	SYP,
	SZL,
	THB,
	TJS,
	TMT,
	TND,
	TOP,
	TRY,
	TTD,
	TWD,
	TZS,
	UAH,
	UGX,
	USD,
	USN,
	UYI,
	UYU,
	UYW,
	UZS,
	VES,
	VND,
	VUV,
	WST,
	XAF,
	XAG,
	XAU,
	XBA,
	XBB,
	XBC,
	XBD,
	XCD,
	XDR,
	XOF,
	XPD,
	XPF,
	XPT,
	XSU,
	XTS,
	XUA,
	XXX,
	YER,
	ZAR,
	ZMW,
	ZWL,
}
